### ISSUE TITLE
Athena Opensearch ListTables fails for opensearch on VPC

### ISSUE THREAD

**Issue by pratikshetty94** [awslabs/aws-athena-query-federation#1047]
# Have set the security group and subnets same as the opensearch. But getting this: Failed to get tables names from lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: Error processing request to list indices: Unable to calculate a request signature: null

# Lambda env variables
auto_discover_endpoint | true
disable_spill_encryption | false
query_scroll_timeout | 60
query_timeout_cluster | 10
query_timeout_search | 720
spill_bucket | bucket-name
spill_prefix | athena-spill

# Error:
Error processing request to list indices: Unable to calculate a request signature: null: java.lang.RuntimeException
java.lang.RuntimeException: Error processing request to list indices: Unable to calculate a request signature: null
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchMetadataHandler.doListTables(ElasticsearchMetadataHandler.java:211)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:250)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)
Caused by: java.lang.RuntimeException: Unable to calculate a request signature: null
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:938)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
	at org.elasticsearch.client.IndicesClient.getAlias(IndicesClient.java:1315)
	at com.amazonaws.athena.connectors.elasticsearch.AwsRestHighLevelClient.getAliases(AwsRestHighLevelClient.java:82)
	at com.amazonaws.athena.connectors.elasticsearch.ElasticsearchMetadataHandler.doListTables(ElasticsearchMetadataHandler.java:196)
	... 3 more
Caused by: com.amazonaws.SdkClientException: Unable to calculate a request signature: null
	at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:109)
	at com.amazonaws.auth.AWS4Signer.newSigningKey(AWS4Signer.java:641)
	at com.amazonaws.auth.AWS4Signer.deriveSigningKey(AWS4Signer.java:404)
	at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:253)
	at com.amazonaws.athena.connectors.elasticsearch.AWSRequestSigningApacheInterceptor.process(AWSRequestSigningApacheInterceptor.java:133)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
	at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.execute(CloseableHttpAsyncClientBase.java:116)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:138)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	... 10 more
Caused by: java.lang.NullPointerException
	at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:104)
	... 21 more

**Comment by akuzin1** [comment]
Thank you for reaching out! 
For immediate remedy I suggest setting the `auto_discover_endpoint` as `false` and then provide `domain_mapping` as an environment variable to the lambda. Then set Master User of the Opensearch Domain as the IAM Role of the Lambda or provide credentials in domain mapping connection string (example below).

_**Example of Domain Mapping:**_
If Master User is not an IAM Role use the following format: `domain1=https://username@password:<domain-endpoint>`
otherwise: `domain1=https://<domain-endpoint>`
and you can provide multiple domain names as such: `domain1=endpoint1,domain2=endpoint2,...`

Please follow up if you have any questions?

**Comment by akuzin1** [comment]
Please upgrade Elasticsearch connector to version 2023.13.1, which should have this issue resolved.
