### ISSUE TITLE
[BUG] Invalid query with Athena Engine v3 with connector DynamoDB

### ISSUE THREAD

**Issue by martin-macak** [awslabs/aws-athena-query-federation#1089]
**Describe the bug**
When Athena is configured with DynamoDB data source and Athena engine is set to v3, DynamoDB queries that use columns mapped to HASH and RANGE keys used in KeyConditionExpression fail with an exception.

```
SELECT col1, col2                         
                  FROM DynamoDB.dynamodb_connector_db.test_table
                  WHERE PK = 'PARTITION'
                    AND SK LIKE 'VALUE#%'
```

fails with engine v3 but works correctly with engine v2

Error displayed in Athena

```
GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:eu-west-1::function:dynamodb-connector] executed in context[S3SpillLocation{bucket='spill_bucket', key='athena-spill/f38b3e0b-469d-4403-bf80-a31966431c38/1c9ea852-2ff1-4626-afd5-a585f72e0c3b', directory=true}] with message[KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: C9UUDRK6R7CNJ6LKM72GFL2A2JVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)]
```

**To Reproduce**
1. Install DynamoDB Lambda connector 
2. Configure DynamoDB data source
3. Configure new Glue database according to https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html
4. Create DynamoDB table with HASH key PK and SORT key SK
5. Create Glue table according to https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html that points to DynamoDB table
6. Execute query that uses WHERE condition that targets PK = 'PARTITION value' AND SK like 'XXX%' so it's used as sort key expression in query
7. Execute with Athena Engine v2 and Athena Engine v3

**Expected behavior**
Query works correctly in both engines

**Screenshots / Exceptions / Errors**

Stack trace 

```
KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: C9UUDRK6R7CNJ6LKM72GFL2A2JVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null): com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBExceptioncom.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: C9UUDRK6R7CNJ6LKM72GFL2A2JVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6470)	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6437)	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:4160)	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:4124)	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.lambda$next$0(DynamoDBRecordHandler.java:311)	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:187)	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:167)	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:311)	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:288)	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:201)	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192)	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158)	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:138)	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) | KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: C9UUDRK6R7CNJ6LKM72GFL2A2JVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null): com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: KeyConditionExpressions must only contain one condition per key (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: C9UUDRK6R7CNJ6LKM72GFL2A2JVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6470) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6437) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:4160) at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:4124) at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.lambda$next$0(DynamoDBRecordHandler.java:311) at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:187) at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:167) at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:311) at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:288) at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:201) at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192) at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158) at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:138) at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)
-- | --
```

Example query 
```
SELECT col1, col2                         
                  FROM DynamoDB.dynamodb_connector_db.test_table
                  WHERE PK = 'PARTITION'
                    AND SK LIKE 'VALUE#%'
```

**Connector Details (please complete the following information):**
 - Version: 2023.8.3
 - DynamoDB
 - Athena query ID: 10b6a616-2920-431f-aa00-c2200a9529fa

**Comment by henrymai** [comment]
Thanks for filing this issue and sorry that this took a while.
I just had a chance to look at it today and put up a PR to fix this issue.

**Comment by henrymai** [comment]
The fix has been merged and I think we'll have a new release out by end of day Friday (or earlier).
I will update this issue again with the released version number once its out.

**Comment by henrymai** [comment]
Version 2023.11.1 of the DynamoDB contains the fix. Please try it out and let me know if you have any other issues.
