### ISSUE TITLE
[BUG] connector not respecting latest glue table schema version with connector Dynamo

### ISSUE THREAD

**Issue by kevduggan** [awslabs/aws-athena-query-federation#1121]
**Describe the bug**
I setup a glue table as per https://docs.aws.amazon.com/athena/latest/ug/connectors-dynamodb.html and used a crawler to generate the schema.
This table had ~ 50 columns so I then manually updated the schema to only map the 18 columns needed.

When querying in athena I can see the correct columns for the new version of the schema
<img width="345" alt="Screenshot_2023-03-16_at_11_26_24" src="https://user-images.githubusercontent.com/3285939/225603227-37ff411c-ee79-4f04-9c7e-6c0768901642.png">

however the query results returns columns I had removed from the latest schema version

seeing this error sporadically in the logs, indicating it is ignoring the glue schema altogether

```
WARN  DynamoDBMetadataHandler:239 - doGetTable: Unable to retrieve table xxx-core from AWSGlue in database/schema xxx n. Falling back to schema inference. If inferred schema is incorrect, create a matching table in Glue to define schema (see README)com.amazonaws.services.glue.model.EntityNotFoundException: Table xxx-core not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 4a341707-39c7-4fe9-bd90-eeff6f1a0980; Proxy: null)	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[task/:?]	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[task/:?]	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:13723) ~[task/:?]	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:13690) ~[task/:?]	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:13679) ~[task/:?]	at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:7921) ~[task/:?]	at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:7890) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:385) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:345) ~[task/:?]	at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.doGetTable(DynamoDBMetadataHandler.java:236) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) ~[task/:?]	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) ~[aws-lambda-java-runtime-0.2.0.jar:?]	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) ~[aws-lambda-java-runtime-0.2.0.jar:?]	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:206) ~[aws-lambda-java-runtime-0.2.0.jar:?]	at lambdainternal.AWSLambda.main(AWSLambda.java:200) ~[aws-lambda-java-runtime-0.2.0.jar:?] | 2023-03-16 10:51:44 e6a41dc0-3a1f-46d0-bb45-df1680fa3ab6 WARN DynamoDBMetadataHandler:239 - doGetTable: Unable to retrieve table xxx-core from AWSGlue in database/schema xxx. Falling back to schema inference. If inferred schema is incorrect, create a matching table in Glue to define schema (see README) com.amazonaws.services.glue.model.EntityNotFoundException: Table xxx-core not found. (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: 4a341707-39c7-4fe9-bd90-eeff6f1a0980; Proxy: null) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[task/:?] at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:13723) ~[task/:?] at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:13690) ~[task/:?] at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:13679) ~[task/:?] at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:7921) ~[task/:?] at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:7890) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:385) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:345) ~[task/:?] at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.doGetTable(DynamoDBMetadataHandler.java:236) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?] at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) ~[task/:?] at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) ~[aws-lambda-java-runtime-0.2.0.jar:?] at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) ~[aws-lambda-java-runtime-0.2.0.jar:?] at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:206) ~[aws-lambda-java-runtime-0.2.0.jar:?] at lambdainternal.AWSLambda.main(AWSLambda.java:200) ~[aws-lambda-java-runtime-0.2.0.jar:?]
-- | --
```

**Expected behavior**
the latest version of the glue table schema to be used during the query

**Connector Details (please complete the following information):**
 - Version: 2023.5.1
 -  Name: dynamo

**Comment by kevduggan** [comment]
not a bug. the clue crawler creates the table with underscores in place of dashes
