### ISSUE TITLE
[QUESTION] Building and installing on local m1 mac, test failures

### ISSUE THREAD

**Issue by nkumarbill** [awslabs/aws-athena-query-federation#1269]
I have a question that I don't think is related to a bug or feature request. 

Trying to build locally and getting test failures. 

Versions:
Maven home: /opt/homebrew/Cellar/maven/3.9.1/libexec
Java version: 11.0.19, vendor: Amazon.com Inc., ~/.sdkman/candidates/java/11.0.19-amzn
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.5", arch: "aarch64", family: "mac"

Here is the output of mvn -X -DtrimStackTrace=false clean install

`[INFO] Running com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandlerTest
May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[1]: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[]: error running job queue
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.almworks.sqlite4java.Internal.tryLoadFromPath(Internal.java:340)
	at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:110)
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
	... 9 more

May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[]: stopped abnormally, reincarnation is not possible for in-memory database
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.112 s <<< FAILURE! - in com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandlerTest
[ERROR] com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandlerTest  Time elapsed: 0.112 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	java.lang.NullPointerException: <no message>
	java.lang.NullPointerException: <no message>
	at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:200)
	at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:248)
	at org.junit.vintage.engine.execution.RunListenerAdapter.reportContainerFinished(RunListenerAdapter.java:114)
	at org.junit.vintage.engine.execution.RunListenerAdapter.testRunFinished(RunListenerAdapter.java:102)
	at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
	at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
	Suppressed: java.lang.NullPointerException
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.initializeMetadataTables(SQLiteDBAccess.java:461)
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:248)
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:217)
		at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:49)
		at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:39)
		at com.amazonaws.athena.connectors.dynamodb.TestBase.setupDatabase(TestBase.java:105)
		at com.amazonaws.athena.connectors.dynamodb.TestBase.setupOnce(TestBase.java:91)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
		at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
		at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
		at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		... 21 more
	Suppressed: java.lang.NullPointerException
		at com.amazonaws.athena.connectors.dynamodb.TestBase.tearDownOnce(TestBase.java:99)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
		at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
		at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
		at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		... 21 more

[INFO] Running com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandlerTest
May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[2]: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[]: error running job queue
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /Users/nigibh.kumar/git/aws-athena-query-federation/athena-dynamodb/native-libs/libsqlite4java-osx-1.0.392.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.almworks.sqlite4java.Internal.tryLoadFromPath(Internal.java:340)
	at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:110)
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
	... 9 more

May 15, 2023 3:22:56 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[]: stopped abnormally, reincarnation is not possible for in-memory database
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandlerTest
[ERROR] com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandlerTest  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (2 failures)
	java.lang.NullPointerException: <no message>
	java.lang.NullPointerException: <no message>
	at org.junit.vintage.engine.execution.TestRun.getStoredResultOrSuccessful(TestRun.java:200)
	at org.junit.vintage.engine.execution.RunListenerAdapter.fireExecutionFinished(RunListenerAdapter.java:248)
	at org.junit.vintage.engine.execution.RunListenerAdapter.reportContainerFinished(RunListenerAdapter.java:114)
	at org.junit.vintage.engine.execution.RunListenerAdapter.testRunFinished(RunListenerAdapter.java:102)
	at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
	at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
	Suppressed: java.lang.NullPointerException
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.initializeMetadataTables(SQLiteDBAccess.java:461)
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:248)
		at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess.<init>(SQLiteDBAccess.java:217)
		at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:49)
		at com.amazonaws.services.dynamodbv2.local.embedded.DynamoDBEmbedded.create(DynamoDBEmbedded.java:39)
		at com.amazonaws.athena.connectors.dynamodb.TestBase.setupDatabase(TestBase.java:105)
		at com.amazonaws.athena.connectors.dynamodb.TestBase.setupOnce(TestBase.java:91)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
		at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
		at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
		at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		... 21 more
	Suppressed: java.lang.NullPointerException
		at com.amazonaws.athena.connectors.dynamodb.TestBase.tearDownOnce(TestBase.java:99)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
		at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
		at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
		at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
		at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
		at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
		at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		... 21 more

[INFO] Running com.amazonaws.athena.connectors.dynamodb.DDBPredicateUtilsTest
2023-05-15 15:22:56  INFO  DDBPredicateUtilsTest:55 - testAliasColumn - enter
2023-05-15 15:22:56  INFO  DDBPredicateUtilsTest:66 - testAliasColumn - exit
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s - in com.amazonaws.athena.connectors.dynamodb.DDBPredicateUtilsTest
[DEBUG] Closing the fork 1 after saying GoodBye.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DynamoDBMetadataHandlerTest Multiple Failures (2 failures)
	java.lang.NullPointerException: <no message>
	java.lang.NullPointerException: <no message>
[ERROR]   DynamoDBRecordHandlerTest Multiple Failures (2 failures)
	java.lang.NullPointerException: <no message>
	java.lang.NullPointerException: <no message>
[INFO] 
[ERROR] Tests run: 15, Failures: 2, Errors: 0, Skipped: 0`

**Comment by nkumarbill** [comment]
I was able to resolve this by including this
`        <dependency>
            <groupId>io.github.ganadist.sqlite4java</groupId>
            <artifactId>libsqlite4java-osx-aarch64</artifactId>
            <version>1.0.392</version>
            <type>dylib</type>
            <scope>test</scope>
        </dependency>`
as a dependency (m1 compatibility issue).
Now I have another:

` Failed to execute goal on project athena-cloudera-hive: Could not resolve dependencies for project com.amazonaws:athena-cloudera-hive:jar:2022.47.1: Failed to collect dependencies at Hive:HiveJDBC42:jar:2.6.15.1018: Failed to read artifact descriptor for Hive:HiveJDBC42:jar:2.6.15.1018: The following artifacts could not be resolved: Hive:HiveJDBC42:pom:2.6.15.1018 (absent): Could not transfer artifact Hive:HiveJDBC42:pom:2.6.15.1018 from/to cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project athena-cloudera-hive: Could not resolve dependencies for project com.amazonaws:athena-cloudera-hive:jar:2022.47.1: Failed to collect dependencies at Hive:HiveJDBC42:jar:2.6.15.1018
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:252)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:145)
`

**Comment by nkumarbill** [comment]
Could not transfer artifact Hive:HiveJDBC42:pom:2.6.15.1018 from/to cloudera (https://repository.cloudera.com/artifactory/cloudera-repos/): transfer failed for https://repository.cloudera.com/artifactory/cloudera-repos/Hive/HiveJDBC42/2.6.15.1018/HiveJDBC42-2.6.15.1018.pom

but i can navigate to the jar fine...

**Comment by hackett123** [comment]
We guarantee build-compatibility with linux machines only. If you have a linux virtual machine, or a Cloud9 instance, you can follow this guide to build the repository in a container - https://github.com/awslabs/aws-athena-query-federation/wiki/Building-aws-athena-query-federation-using-container_env
