### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: org/apache/http/conn/DnsResolver

### ISSUE THREAD

**Issue by danielhaviv** [awslabs/aws-athena-query-federation#131]
I'm modifying the the Example connector to read a single Parquet file (for testing purposes).
mvn package passes without a problem but when running the validate_connector utility it fails with the following stack trace:

```
org/apache/http/conn/DnsResolver: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/apache/http/conn/DnsResolver
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.<init>(ApacheHttpClientFactory.java:41)
	at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:157)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:192)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:211)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.<init>(AWSSecretsManagerClient.java:197)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:61)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.build(AWSSecretsManagerClientBuilder.java:27)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClientBuilder.defaultClient(AWSSecretsManagerClientBuilder.java:45)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.<init>(MetadataHandler.java:137)
	at com.amazonaws.connectors.athena.example.ExampleMetadataHandler.<init>(ExampleMetadataHandler.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.DnsResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

I can include it in my pom, but should I?

**Comment by avirtuos** [comment]
Have you made any changes to the parent pom, the athena-federation-sdk pom, or the pom for the validator?

@sethtdenney can you confirm if the validator works right now or if we broke it inadvertently or if Daniels changes may be affecting the dependency tree.

**Comment by danielhaviv** [comment]
Haven't done any changes to the afformentioned poms

**Comment by avirtuos** [comment]
Can you give more info on where this stacktrace is coming from? the full validator output would be useful. This error upon deeper inspection seems to be comming from your lambda function and is being identified by the validator (e.g. the validator is doing its job correctly but your lambda failed valiation).

**Comment by avirtuos** [comment]
If you are still having this issue, please reopen this request.
