### ISSUE TITLE
[QUESTION] com.amazonaws.services.lambda.invoke.LambdaFunctionException: Expected a MetadataRequest but found class com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest

### ISSUE THREAD

**Issue by danielhaviv** [awslabs/aws-athena-query-federation#133]
I'm following the Example connector code to implement my own connector, and in GetSplitResponse I'm returning the following:

```
        Split split = Split.newBuilder(makeSpillLocation(request), makeEncryptionKey())
                .add("bucket", "dhavivresearch")
                .add("key", "/parquet/part-00005-bca60778-1651-4d12-a7ef-4d7320649530-c000.snappy.parquet")
                .build();
        splits.add(split);
        return new GetSplitsResponse(catalogName, splits);

```

When running validation I'm hitting the following exception:

```
2020-03-27 12:19:21  INFO  LambdaMetadataProvider:93 - Submitting request: ReadRecordsRequest{queryId=connector_test, tableName=TableName{schemaName=delta, tableName=demotable}, schema=Schema<author: Utf8, body: Utf8>, split=Split{spillLocation=S3SpillLocation{bucket='null', key='athena-federation-spill/e6fd8a4f-3f1a-43a8-b1f5-73c47e384a12_unknown/ec62d21d-ebd0-4819-95d6-73dede5da55d', directory=true}, encryptionKey=<hidden>, properties={bucket=dhavivresearch, key=/delta/part-00005-bca60778-1651-4d12-a7ef-4d7320649530-c000.snappy.parquet}}, requestType=READ_RECORDS, catalogName=650fc065-8138-4ff5-9cc4-ba5651ef22a6_unknown, maxBlockSize=16000000, maxInlineBlockSize=5242880, constraints=Constraints{summary={}}}
2020-03-27 12:19:23  ERROR ConnectorValidator:358 - ==================================================
2020-03-27 12:19:23  ERROR ConnectorValidator:359 - Error Encountered During Validation!
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Expected a MetadataRequest but found class com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest
	at com.amazonaws.athena.connector.validation.LambdaRecordProvider.readRecords(LambdaRecordProvider.java:99) ~[athena-federation-sdk-tools-1.0-withdep.jar:?]
	at com.amazonaws.athena.connector.validation.ConnectorValidator.readRecords(ConnectorValidator.java:302) [athena-federation-sdk-tools-1.0-withdep.jar:?]
	at com.amazonaws.athena.connector.validation.ConnectorValidator.main(ConnectorValidator.java:136) [athena-federation-sdk-tools-1.0-withdep.jar:?]
Caused by: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Expected a MetadataRequest but found class com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest
	at com.amazonaws.athena.connector.validation.LambdaRecordProvider$RecordService.com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.handleRequest(MetadataHandler.java:209)(Unknown Source) ~[athena-federation-sdk-tools-1.0-withdep.jar:?]
2020-03-27 12:19:23  ERROR ConnectorValidator:360 - ==================================================

```
Am I doing something wrong?

**Comment by avirtuos** [comment]
@danielhaviv the error seems to indicate that either: you are passing the wrong arguments to the validator or your lambda function is not properly implementing the specification and ReadRecords requests are being routed to the MetadataHandler class. Is it possible for you to share your fork with us?  If you are not able to share it publicly on github you can email me at virtuoso[at]amazon.com 

Alternatively you can share logs from the Lambda function (they get written to CloudWatch logs) and we can try to ascertain whats going on from that if you would rather not share the code.

**Comment by danielhaviv** [comment]
@avirtuos I tried the Example connector, uncommented the code inside the methods and ran it, it fails with the same error:```
2020-03-28 13:36:39  INFO  LambdaMetadataProvider:217 - Received response: GetSplitsResponse{splitSize=1, continuationToken='null'}
2020-03-28 13:36:39  INFO  ConnectorValidator:277 - Found 1 splits in batch.
2020-03-28 13:36:39  INFO  ConnectorValidator:301 - Executing randomly selected split with properties: {month=11, year=2017, day=30}
2020-03-28 13:36:39  INFO  LambdaMetadataProvider:81 - Submitting ReadRecordsRequest with ID e4ea25fc-c574-4954-a08a-626329152713_unknown
2020-03-28 13:36:39  INFO  LambdaMetadataProvider:93 - Submitting request: ReadRecordsRequest{queryId=connector_test, tableName=TableName{schemaName=schema1, tableName=table1}, schema=Schema<account_id: Utf8, month: Int(32, true), encrypted_payload: Utf8, year: Int(32, true), day: Int(32, true), transaction: Struct<id: Int(32, true), completed: Bool>>(metadata: {account_id=The account_id used for this payment., month=The month that the payment took place in., encrypted_payload=A special encrypted payload., year=The year that the payment took place in., partitionCols=year,month,day, day=The day that the payment took place in., transaction=The payment transaction details.}), split=Split{spillLocation=S3SpillLocation{bucket='null', key='athena-federation-spill/28b4f581-1dfe-4a66-8182-6d1ab7002b8a_unknown/ab5ea7c0-e4dd-4288-a04f-5751fe44ffe6', directory=true}, encryptionKey=<hidden>, properties={month=11, year=2017, day=30}}, requestType=READ_RECORDS, catalogName=e4ea25fc-c574-4954-a08a-626329152713_unknown, maxBlockSize=16000000, maxInlineBlockSize=5242880, constraints=Constraints{summary={}}}
2020-03-28 13:36:41  ERROR ConnectorValidator:358 - ==================================================
2020-03-28 13:36:41  ERROR ConnectorValidator:359 - Error Encountered During Validation!
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Expected a MetadataRequest but found class com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest
	at com.amazonaws.athena.connector.validation.LambdaRecordProvider.readRecords(LambdaRecordProvider.java:100) ~[athena-federation-sdk-tools-1.0-withdep.jar:?]
	at com.amazonaws.athena.connector.validation.ConnectorValidator.readRecords(ConnectorValidator.java:302) [athena-federation-sdk-tools-1.0-withdep.jar:?]
	at com.amazonaws.athena.connector.validation.ConnectorValidator.main(ConnectorValidator.java:136) [athena-federation-sdk-tools-1.0-withdep.jar:?]
Caused by: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Expected a MetadataRequest but found class com.amazonaws.athena.connector.lambda.records.ReadRecordsRequest
	at com.amazonaws.athena.connector.validation.LambdaRecordProvider$RecordService.com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.handleRequest(MetadataHandler.java:209)(Unknown Source) ~[athena-federation-sdk-tools-1.0-withdep.jar:?]
2020-03-28 13:36:41  ERROR ConnectorValidator:360 - ==================================================
```

**Comment by avirtuos** [comment]
What class are you setting as the entry point for the Lambda and can you show us the command you are running for validation?

**Comment by danielhaviv** [comment]
com.amazonaws.connectors.athena.example.ExampleMetadataHandler

`./tools/validate_connector.sh --lambda-func connector_test --schema schema1 --table table1`

**Comment by avirtuos** [comment]
The error suggests that CompositeRequestHandler is not being used as the entry point but rather MetadataHandler is only.

**Comment by avirtuos** [comment]
> com.amazonaws.connectors.athena.example.ExampleMetadataHandler
> 
> `./tools/validate_connector.sh --lambda-func connector_test --schema schema1 --table table1`

That's the issue, it should be the composite handler which knows when to delegate to either rmatadata or read records.

**Comment by danielhaviv** [comment]
Got it 
:man_facepalming:

Thanks for all the support :)
