### ISSUE TITLE
[BUG] SSM connection error with connector oracle connector

### ISSUE THREAD

**Issue by Techievena** [awslabs/aws-athena-query-federation#1337]
**Describe the bug**
Facing the following issue for oracle jdbc connector:
```
Unable to execute HTTP request: Connect to secretsmanager.eu-west-1.amazonaws.com:443 [secretsmanager.eu-west-1.amazonaws.com/34.240.33.6, secretsmanager.eu-west-1.amazonaws.com/34.254.79.238, secretsmanager.eu-west-1.amazonaws.com/52.16.54.217] failed: connect timed out: com.amazonaws.SdkClientException
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to secretsmanager.eu-west-1.amazonaws.com:443 [secretsmanager.eu-west-1.amazonaws.com/34.240.33.6, secretsmanager.eu-west-1.amazonaws.com/34.254.79.238, secretsmanager.eu-west-1.amazonaws.com/52.16.54.217] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.doInvoke(AWSSecretsManagerClient.java:2770)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.invoke(AWSSecretsManagerClient.java:2737)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.invoke(AWSSecretsManagerClient.java:2726)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.executeGetSecretValue(AWSSecretsManagerClient.java:1089)
	at com.amazonaws.services.secretsmanager.AWSSecretsManagerClient.getSecretValue(AWSSecretsManagerClient.java:1058)
	at com.amazonaws.athena.connector.lambda.security.CachableSecretsManager.getSecret(CachableSecretsManager.java:100)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.getSecret(MetadataHandler.java:198)
	at com.amazonaws.athena.connectors.jdbc.manager.JdbcMetadataHandler.getCredentialProvider(JdbcMetadataHandler.java:127)
	at com.amazonaws.athena.connectors.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:137)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:259)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:144)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:112)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to secretsmanager.eu-west-1.amazonaws.com:443 [secretsmanager.eu-west-1.amazonaws.com/34.240.33.6, secretsmanager.eu-west-1.amazonaws.com/34.254.79.238, secretsmanager.eu-west-1.amazonaws.com/52.16.54.217] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	... 19 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 35 more
```
Please any help is deeply appreciated!

I have been struggling with this for quite a long time. I thought maybe it was a permission issue so manual updated role to allow secretsmanager:* for the lambda function.

Also had created an EC2 instance in same VPC, subnet and security-group. It was successfully connecting for command - telnet secretsmanager.eu-west-1.amazonaws.com 443

**Comment by burhan94** [comment]
Hi, 

you'll need to set up a VPC endpoint:
https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html

**Comment by Techievena** [comment]
@burhan94 Thanks a lot! Actually I have already created VPC endpoint for secrets manager with private DNS name, full access and am still facing the issue.

For the lambda function, the subnet is connected to internet gateway, but the security group only allows limited inbound connections. I have added same vpc, region, subnet, security group for VPC endpoint created.

Is there any issue in this configuration?

**Comment by Techievena** [comment]
Hello @burhan94 

I tried setting all possible combinations I found over internet and still no luck. Can you please help me here?
