### ISSUE TITLE
[BUG] Lambda s3 timeout error with connector AthenaJDBCConnector

### ISSUE THREAD

**Issue by tharsha18** [awslabs/aws-athena-query-federation#134]
**Describe the bug**
When using the AthenaJDBCConnector to federate Athena to Redshift, some queries have worked fine but several other queries error out with S3 connect timed out error @ ~1min into job start time. I looked at the lambda logs and clearly see that Redshift returned 4M rows and that it is spilling it to spill-bucket in S3 following which i see the error. See the lambda cloudwatch log output below under Error section for more details. 

**To Reproduce**
1. Go to 'Athena'
2. Run a query with a few joins and predicates for tables in Redshift
3. See s3 timeout error.

**Expected behavior**
The expected behavior is the query returns results without any errors.

**Screenshots / Exceptions / Errors**
2020-03-31 00:04:37 INFO S3BlockSpiller:312 - write: Started spilling block of size 16000224 bytes 2020-03-31 00:04:37 WARN AmazonS3Client:1766 - No content length specified for stream data. Stream contents will be buffered in memory and could result in out of memory errors. 2020-03-31 00:04:38 6f6b4602-215f-498c-9c0f-076aaea874b7 INFO JdbcRecordHandler:146 - 4000000 rows returned by database. 2020-03-31 00:05:15 WARN S3BlockSpiller:323 - write: Encountered error while writing block. com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/52.217.46.182] failed: connect timed out at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1164) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1110) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675) ~[task/:?] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657) ~[task/:?] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1807) ~[task/:?] at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1665) ~[task/:?] at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.write(S3BlockSpiller.java:313) ~[task/:?] at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.lambda$spillBlock$0(S3BlockSpiller.java:367) ~[task/:?] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com:443 [s3.amazonaws.com/52.217.46.182] failed: connect timed out

**Connector Details (please complete the following information):**
 - Version: version 2020.4.1
 - Name : AthenaJDBCConnector
 - Athena Query IDs [if applicable] with Query Id: 1588f8d6-ca5a-4104-8069-90dff542519f or
![2020-03-31_10-00-20](https://user-images.githubusercontent.com/50037595/78034998-7f561e80-7336-11ea-91f6-cc5eaf916d4a.jpg)
 Query Id: 4b954e52-9c24-4418-be72-4031b4287288 or 

**Additional context**

**Comment by avirtuos** [comment]
Is your lambda function running in a VPC and subnet that has a route to S3? This error usually happens when there is no path to S3. A quick way to check is by adding an S3 vpc endpoint to the subnet in question.

**Comment by tharsha18** [comment]
Issue resolved after adding S3 endpoint to the VPC.
