### ISSUE TITLE
[BUG] Null 'List' within a Struct fails with all connectors

### ISSUE THREAD

**Issue by avirtuos** [awslabs/aws-athena-query-federation#166]
**Describe the bug**
It is not possible to read or write a null List field value when the List is part of a Struct. 

`2020-04-16 18:00:30 XXXXXXX WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: Error while processing field XXXXX
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:158) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174) ~[task/:?]
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.readWithConstraint(DocDBRecordHandler.java:136) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:191) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:157) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:906) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119) [LambdaJavaRTEntry-1.0.jar:?]
Caused by: java.lang.NullPointerException
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeStruct(BlockUtils.java:584) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:181) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218) ~[task/:?]
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:147) ~[task/:?]
	... 12 more
Error while processing field Vendor: java.lang.RuntimeException
java.lang.RuntimeException: Error while processing field XXXXX
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:158)
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174)
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.readWithConstraint(DocDBRecordHandler.java:136)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:191)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:157)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
Caused by: java.lang.NullPointerException
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeStruct(BlockUtils.java:584)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:181)
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218)
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:147)
	... 6 more`

**Comment by avirtuos** [comment]
Merged.
