### ISSUE TITLE
[QUESTION] How to integrate Clickhouse DB with Athena MySQL Connector

### ISSUE THREAD

**Issue by bishrtabbaa** [awslabs/aws-athena-query-federation#1754]
Hello, I am trying to integrate **Athena** federated query engine (FQE) with a [**Clickhouse**](https://clickhouse.com/docs/en/integrations/mysql) DB data source using the CH MySQL wire protocol adapter.  

Working backwards... the goal is to minimize data movement and ETL and allow users/product microservices to perform ad-hoc and canonical queries against data both in S3 and **Clickhouse** (CH) using Athena's FQE and governed through **Lake Formation**

- **SW** = `Clickhouse local v24.2.1.505`
- **CFG** = 1 singleton node with users granted permissions to read/write tables
- **HW** = `Amazon EC2`
- **Scenario**
-- CH vanilla protocol works locally and remotely [a] 
-- MySQL protocol adapter works both locally and remotely [b]
-- Configured the Athena MySQL JDBC Connector and confirmed in both the Athena Lambda (client) and CH [server] that 1/requests and response are getting thru, 2/authentication succeeds, etc, **_however_** upon 3/Athena listing the CH catalogs and schemas .. the connector fails even though the underlying schema and table list queries succeed when run in mode b mentioned above.

- **Logs**

**Clickhouse** - https://github.com/ClickHouse/ClickHouse/issues/12701

**Athena**
```
java.sql.SQLException: Buffer length is less than expected payload length.: java.lang.RuntimeException
java.lang.RuntimeException: java.sql.SQLException: Buffer length is less than expected payload length.
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:117)
Caused by: java.sql.SQLException: Buffer length is less than expected payload length.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:438)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:189)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at com.amazonaws.athena.connectors.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:90)
	at com.amazonaws.athena.connectors.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:140)
	at com.amazonaws.athena.connectors.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:110)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:259)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:144)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:112)
```

**Comment by macohen** [comment]
@bishrtabbaa are you up for creating a custom connector for clickhouse using their JDBC driver?

**Comment by bishrtabbaa** [comment]
Yes.  Submitted PR to the team.  Grateful for the feedback and support.

https://github.com/awslabs/aws-athena-query-federation/pull/1770
