### ISSUE TITLE
[QUESTION] Getting error - Client's SerDe is not upgraded to latest version, defaulting to V4

### ISSUE THREAD

**Issue by avoidik** [awslabs/aws-athena-query-federation#1903]
Hello there,

I have a question that I don't think is related to a bug or feature request. We're getting the following error:

```
2024-04-09 13:30:14 5b83a0f7-aaa6-4d7e-b26f-bd7b2c2330d2 WARN  CompositeHandler:106 - Client's SerDe is not upgraded to latest version, defaulting to V4:
java.lang.IllegalStateException: Expected field name token but got END_OBJECT
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:239) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.v5.ConstraintsSerDeV5$Deserializer.doDeserialize(ConstraintsSerDeV5.java:147) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.v5.ConstraintsSerDeV5$Deserializer.doDeserialize(ConstraintsSerDeV5.java:98) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.deserialize(BaseDeserializer.java:51) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.v2.ReadRecordsRequestSerDe$Deserializer.doTypedDeserialize(ReadRecordsRequestSerDe.java:151) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.v2.ReadRecordsRequestSerDe$Deserializer.doTypedDeserialize(ReadRecordsRequestSerDe.java:108) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:59) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49) ~[task/:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74) ~[task/:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[task/:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899) ~[task/:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3907) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:196) [aws-lambda-java-runtime-0.2.0.jar:?]
```

could you please suggest what could be wrong, and how to fix it? this is a lambda function from [athena-dynamodb](https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-dynamodb) connector (version 2024.10.1)

regards

**Comment by AbdulR3hman** [comment]
Hi, this is a warning, there is not much to worry about here.
