### ISSUE TITLE
[BUG] Illegal hex characters in escape (%) pattern with connector JDBC

### ISSUE THREAD

**Issue by pian0** [awslabs/aws-athena-query-federation#195]
The data connector logs an exception if the password in secrets manager contains a hex escape sequence. Automatic password rotation in secrets manager can contain % as a special character. I'm filing this as a bug because the documentation strongly recommends using Secrets Manager with rotation, but some passwords that will be generated cause the connection to bomb.

**To Reproduce**
1. Create a data connector lambda that gets its credentials from AWS Secrets Manager with rotation enabled
2. Rotate the retrieve the password until a password containing % is generated
3. Confirm the password was rotated by logging into RDS with the password.
4. Query the data connector in Athena

**Expected behavior**
Tables and schemas should appear in Athena results

**Exceptions**
For example, this generated password contained the substring `%}>`

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "}>"
	at java.net.URLDecoder.decode(URLDecoder.java:194) ~[?:1.8.0_201]
	at org.postgresql.util.URLCoder.decode(URLCoder.java:33) ~[task/:?]
	at org.postgresql.Driver.parseURL(Driver.java:628) ~[task/:?]
	at org.postgresql.Driver.connect(Driver.java:241) ~[task/:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_201]
	at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_201]
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:102) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:231) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:909) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:119) [LambdaJavaRTEntry-1.0.jar:?]
```

**Connector Details (please complete the following information):**
 - Version: 2020.20.1
 - Name: JDBC

**Comment by avirtuos** [comment]
Thanks for raising this.

**Comment by avirtuos** [comment]
I actually think I have a fix ready. Are you comfortable building and deploying a connector from code using our tutorial ( https://github.com/awslabs/aws-athena-query-federation/wiki/How_To_Build_A_Connector_or_UDF )? 

If yes, here is the pull request that you can apply to your local branch.

https://github.com/awslabs/aws-athena-query-federation/pull/196

**Comment by nblomquist** [comment]
Is this ever going to be fixed?
I just deployed the AthenaJdbcConnector serverless application and it failed because the password in the secret had a % sign. Autogenerated passwords in Secrets shouldn't cause issues since Secrets are pushed heavily for this.

**Comment by avirtuos** [comment]
Ill get back to you. I thought we had merged this. my mistake.

**Comment by avirtuos** [comment]
@burhan94 will be getting this pushed ASAP, hopefully in the next couple days (max). He will update this issue once he starts on it.

**Comment by nblomquist** [comment]
Ok, this will go to the AWS _Serverless Application Repository_ when it is merged/tested/pushed?
Now I have to go figure out how to redeploy that.

Thanks for the quick response!

**Comment by burhan94** [comment]
Hi

Yes, I will be cutting a new release and will update the SAR by early next week.

**Comment by avirtuos** [comment]
This has been merged
