### ISSUE TITLE
[BUG] END_OBJECT: java.lang.IllegalStateException with connector JDBC MySQL

### ISSUE THREAD

**Issue by batrahs** [awslabs/aws-athena-query-federation#223]
**Describe the bug**
JDBC MySQL connector is failing with exception "END_OBJECT: java.lang.IllegalStateException" 

**To Reproduce**
1. Create Data Source for MySQL
2. Try to connect to this DataSource in Athena console
3. No Databases will be displayed and in Cloud Watch log for lambda you will get this error

Error may be with other JDBC data sources as well. However i have checked with mySQL and one custom JDBC Connector that i was working on. It seems to be caused by changes to schema for "PingRequest" due to change "6bd29a5". JDBC Connectors do no pass "arn" and it fails because of this.

**Expected behaviour**
Connection to data source should succeeded 

**Screenshots / Exceptions / Errors**
Expected field name token but got END_OBJECT: java.lang.IllegalStateException
java.lang.IllegalStateException: Expected field name token but got END_OBJECT
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:225)
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getNextStringField(BaseDeserializer.java:82)
	at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.doDeserialize(FederatedIdentitySerDe.java:103)
	at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.deserialize(FederatedIdentitySerDe.java:84)
	at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:96)
	at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize(PingRequestSerDe.java:72)
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:59)
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)

**Connector Details (please complete the following information):**
 - Version: latest
 - Name : jdbc
 - Athena Query IDs : 

**Additional context**
None

**Comment by avirtuos** [comment]
@burhan94 can you run with this issue? Get a second opinion from @atennak1 if you need it. I'm worried this is indicative of a non-backwards compatible serialization change from when we enhanced FederatedIdentity.

@batrahs What version of the connector are you using? latest is not a version I recognize, please confirm the specific version. If you are unsure how to do that, you can check the tags on the Lambda function.

**Comment by batrahs** [comment]
@avirtuos lambda version in tags is 2020.19.1. However i have recompiled JDBC connector from latest repo "c233704" and updated lambda and it breaks it.

**Comment by atennak1** [comment]
Looks like need to release the Athena-side changes first and that's already in progress and should finish soon.  Will keep this issue updated.

**Comment by VISHAL-PERIYASAMY** [comment]
[BUG] Expected field name token but got END_OBJECT: java.lang.IllegalStateException
java.lang.IllegalStateException: Expected field name token but got END_OBJECT
at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:221)
at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getNextStringField(BaseDeserializer.java:82)
at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.doDeserialize (FederatedIdentitySerDe.java:103)
at com.amazonaws.athena.connector.lambda.serde.FederatedIdentitySerDe$Deserializer.deserialize (FederatedIdentitySerDe.java:84)
at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize (PingRequestSerDe.java:96)
at com.amazonaws.athena.connector.lambda.serde.PingRequestSerDe$Deserializer.doTypedDeserialize (PingRequestSerDe.java:72)
at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:59)
at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType (DelegatingDeserializer.java:49)
at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99)

Facing same issue when connecting to DynamoDB from athena

**Comment by atennak1** [comment]
Using the releases in Serverless App Repo or checking out commit 81eab5ca025b4ab1828d1ecc129e8148afeca2c4 should unblock you

**Comment by burhan94** [comment]
I've reverted the latest commit for now. In the future, please use the commits with release tags when using this package.
