### ISSUE TITLE
[BUG] DynamoDB connector can't handle array<bigint>

### ISSUE THREAD

**Issue by beaksandclaws** [awslabs/aws-athena-query-federation#248]
**Describe the bug**
I have a DynamoDB table that has the column `dataset_ids`, which is defined as a NumberSet. In the respective AWS Glue table schema that I've created for that dynamo table, I've defined that column as an `array<bigint>`. When I try to run the following query with Athena, I receive an error (stacktrace below):

```SELECT * FROM "dynamo-db-catalog"."default"."[redacted]" WHERE contains(dataset_ids, 104)```

**To Reproduce**
1. Create a dynamo table called `array_test`,  in which you have an item that has a key called `dataset_ids` with value `[104]`.
2. Create an AWS Glue schema for the DynamoDB table, defining `dataset_ids` column as an `array<bigint>`.
3. Query the table using athena: `SELECT * FROM "[catalog name]"."default"."athena_test" WHERE contains(dataset_ids, 104)`

**Expected behavior**
Successful query.

**Screenshots / Exceptions / Errors**
Stack trace from CloudWatch:
```
2020-09-14 17:53:50 cb6c86aa-ebb4-4bd0-a669-024e9d8980df WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: Error while processing field dataset_ids
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$1(DynamoDBRecordHandler.java:193) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174) ~[task/:?]
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:150) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
Caused by: java.lang.RuntimeException: Unable to write value for field null_vector using value 239
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeListValue(BlockUtils.java:859) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeList(BlockUtils.java:580) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:173) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218) ~[task/:?]
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$1(DynamoDBRecordHandler.java:172) ~[task/:?]
	... 12 more
Caused by: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Long
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeListValue(BlockUtils.java:793) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeList(BlockUtils.java:580) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:173) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218) ~[task/:?]
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$1(DynamoDBRecordHandler.java:172) ~[task/:?]
	... 12 more
```

**Connector Details (please complete the following information):**
 - Version: 2020.33.1
 - Name: serverlessrepo-AthenaDynamoDBConnector
 - Athena Query IDs
    - 232c5c4b-d9b1-41ee-b55d-180857879430.

**Additional context**
- Originally the column in AWS Glue was of type `set`, but I don't think that's supported at the moment.
- I've also tried setting the type to `array<int>` just to see if that would change anything, but I get the same error.

**Comment by shurvitz** [comment]
Hi @beaksandclaws, thanks for reporting the issue. We're aware of a problem with data conversion from DDB Numeric type. As a workaround, until we're able to address this issue, you can define the column in the Glue schema as `array<string>`.  It will display the correct results.

**Comment by beaksandclaws** [comment]
That workaround worked, thanks!
