### ISSUE TITLE
[QUESTION] Federated query with external Postgres Database

### ISSUE THREAD

**Issue by igorsechyn** [awslabs/aws-athena-query-federation#286]
I have a question that I don't think is related to a bug or feature request. 

I am trying to setup federated query with external Postgres database, that is not hosted in AWS. I followed instructions from documentation and getting following exception in my Lambda:
```
0: org.postgresql.util.PSQLException: The connection attempt failed.: java.lang.RuntimeException
java.lang.RuntimeException: 0: org.postgresql.util.PSQLException: The connection attempt failed.
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:105)
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129)
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100
-- | --
```
I verified that lambda function is deployed in a public subnet with access to internet and that database can be accessed from public internet. Any help would be appreciated.

**Comment by igorsechyn** [comment]
Hey, I have given up on it a long time ago. I guess it can be closed

**Comment by ykrystal** [comment]
Sorry for the lack of response here. I will close this ticket but please reopen if you encounter problems in the future. Thank you!
