### ISSUE TITLE
[BUG] ClassCastException when using DATE literal with JDBC Postgres connector

### ISSUE THREAD

**Issue by Meosit** [awslabs/aws-athena-query-federation#330]
**Description**
With a deployed PostGreSql JDBC connector (can't test with other JDBC databases), when using conditions like `some_date_field = DATE '2021-01-04'` the query fails with a `java.lang.ClassCastException:
java.lang.Integer cannot be cast to org.joda.time.LocalDateTime`. 

This happens only for `Date(DAY)` arrow type, not `Date(MILLISECOND)` and possibly can be related to [this line of code](https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-jdbc/src/main/java/com/amazonaws/connectors/athena/jdbc/postgresql/PostGreSqlMetadataHandler.java#L253) which may need to be changed to `DATEMILLI` minor type.

**Temporary workaround**

Just use a `TIMESTAMP '2021-01-04'` literals which will do the correct comparison but using `Date(MILLISECOND)` arrow type.

**Exception**

```
2021-01-04 12:04:03 aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee WARN  CompositeHandler:104 - handleRequest: Completed with an exception. 
java.lang.ClassCastException: java.lang.Integer cannot be cast to org.joda.time.LocalDateTime
    at com.amazonaws.connectors.athena.jdbc.manager.JdbcSplitQueryBuilder.buildSql(JdbcSplitQueryBuilder.java:151) ~[task/:?]
    at com.amazonaws.connectors.athena.jdbc.postgresql.PostGreSqlRecordHandler.buildSplitSql(PostGreSqlRecordHandler.java:86) ~[task/:?]
    at com.amazonaws.connectors.athena.jdbc.manager.JdbcRecordHandler.readWithConstraint(JdbcRecordHandler.java:137) ~[task/:?]
    at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192) ~[task/:?]
    at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158) ~[task/:?]
    at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]
    at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
    at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
    at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:341) [LambdaSandboxJava-1.0.jar:?]
    at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
    at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
    at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
```

**To Reproduce**
Deploy such connector and run any query which have `some_date_field = DATE '2021-01-04'` in `WHERE` clause

**Comment by shurvitz** [comment]
@Meosit, thanks for reporting the issue. I'll take a look.

**Comment by shurvitz** [comment]
@Meosit can you share the query ID and CloudWatch logs?

**Comment by shurvitz** [comment]
https://github.com/awslabs/aws-athena-query-federation/pull/332 will fix this issue. If you are still using the preview workgroup in Athena, you should create/use a new Workgroup set to `Athena engine version 2` (for more information on the latter, see [Athena Engine Versioning](https://docs.aws.amazon.com/athena/latest/ug/engine-versions.html)).

**Comment by avirtuos** [comment]
fix has been merged. Thanks for reporting this. The fix is available in our repository and will make its way into our next production release. If you need it now, you can build and deploy the connector using the instructions in the wiki.
