### ISSUE TITLE
[BUG] Elasticsearch Connector does not work with VPC

### ISSUE THREAD

**Issue by micah-williamson** [awslabs/aws-athena-query-federation#340]
**Describe the bug**
When using the connector with cluster inside of a vpc, the connector does not work.

Any request made to elasticsearch itself will fail to sign with a message like:
```
java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Error processing request to list indices: Unable to calculate a request signature: null
```

Full stack trace of which:
```
Error processing request to list indices: Unable to calculate a request signature: null: java.lang.RuntimeException
java.lang.RuntimeException: Error processing request to list indices: Unable to calculate a request signature: null
	at com.amazonaws.connectors.athena.elasticsearch.ElasticsearchMetadataHandler.doListTables(ElasticsearchMetadataHandler.java:211)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:243)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
Caused by: java.lang.RuntimeException: Unable to calculate a request signature: null
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:812)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373)
	at org.elasticsearch.client.IndicesClient.getAlias(IndicesClient.java:986)
	at com.amazonaws.connectors.athena.elasticsearch.AwsRestHighLevelClient.getAliases(AwsRestHighLevelClient.java:82)
	at com.amazonaws.connectors.athena.elasticsearch.ElasticsearchMetadataHandler.doListTables(ElasticsearchMetadataHandler.java:196)
	... 3 more
Caused by: com.amazonaws.SdkClientException: Unable to calculate a request signature: null
	at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:109)
	at com.amazonaws.auth.AWS4Signer.newSigningKey(AWS4Signer.java:641)
	at com.amazonaws.auth.AWS4Signer.deriveSigningKey(AWS4Signer.java:404)
	at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:253)
	at com.amazonaws.connectors.athena.elasticsearch.AWSRequestSigningApacheInterceptor.process(AWSRequestSigningApacheInterceptor.java:128)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
	at org.apache.http.impl.nio.client.MainClientExec.prepareRequest(MainClientExec.java:520)
	at org.apache.http.impl.nio.client.MainClientExec.prepare(MainClientExec.java:146)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:128)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:221)
	... 10 more
Caused by: java.lang.NullPointerException
	at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:104)
	... 20 more
```

The reason being is because a cluster within a vpc does not have an endpoint, but endpoint**s**.
My pull request shows what I mean:

https://github.com/awslabs/aws-athena-query-federation/pull/339

I'm not sure what other problems are caused by having a domain within the VPC. Getting this project to run is not trivial. The setup, install, and publish instructions are invalid for my dev environment (Mac) and even for a fresh AmazonLinux2 EC2. The `./tools/prepare_dev_env.sh` script throws several errors (on linux. i know it's not compatible with mac), and running `mvn clean install` in the elasticsearch project throws this error (on mac and linux):

```
[ERROR] Failed to execute goal on project athena-elasticsearch: Could not resolve dependencies for project com.amazonaws:athena-elasticsearch:jar:1.0: Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1: Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1: Could not find artifact com.amazonaws:aws-athena-query-federation:pom:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by burhan94** [comment]
Hi, 

So the ElasticSearch connector doesn't support VPC at this time. We can definitely add this as a feature request. 

As for your build issues, can you please let us know exactly what issues you were having so that I can potentially make it easier for you and other users to use? As for building the connector, you have to build the federation sdk first. We haven't uploaded the sdk to maven central yet. 

sdk can be found in this module: https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-federation-sdk

**Comment by iamchairs** [comment]
I followed the instructions here:
https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-elasticsearch#deploying-the-connector

**Comment by npow** [comment]
Hi, I encountered the same issue about "could not resolve dependencies":
```
[ERROR] Failed to execute goal on project athena-elasticsearch:
Could not resolve dependencies for project com.amazonaws:athena-elasticsearch:jar:1.0:
Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1:
Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1:
Could not find artifact com.amazonaws:aws-athena-query-federation:pom:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

After checking out this repo (aws-athena-query-federation), I ran the following commands:
```
cd athena-federation-sdk
mvn clean install
cd ..
cd athena-elasticsearch
mvn clean install
```

upon which I got the error.

**Comment by avirtuos** [comment]
> Hi, I encountered the same issue about "could not resolve dependencies":
> 
> ```
> [ERROR] Failed to execute goal on project athena-elasticsearch:
> Could not resolve dependencies for project com.amazonaws:athena-elasticsearch:jar:1.0:
> Failed to collect dependencies at com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1:
> Failed to read artifact descriptor for com.amazonaws:aws-athena-federation-sdk:jar:2020.51.1:
> Could not find artifact com.amazonaws:aws-athena-query-federation:pom:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> ```
> 
> After checking out this repo (aws-athena-query-federation), I ran the following commands:
> 
> ```
> cd athena-federation-sdk
> mvn clean install
> cd ..
> cd athena-elasticsearch
> mvn clean install
> ```
> 
> upon which I got the error.

this error is different than what was reported in the original post. This is a build time issue. if you can share the fully text of your commands we can help. I suspect the build of the federation SDK failed or did not run. Please open a new issue to discuss that topic.

**Comment by avirtuos** [comment]
@shurvitz can you look at the oriignal issue mentioned in this issue about VPC connectivity and signing errors. That seems strange to me.

**Comment by shurvitz** [comment]
The Elasticsearch connector in its present form does not support a VPC configuration, and will need to be enhanced to support the latter. We will prioritize this enhancement in the near future.

**Comment by stefan-novak-brt** [comment]
Any luck with this?

I came across the same issue on 5/6/2022 after creating an AWS OpenSearch cluster and attempting to leverage the AthenaElasticsearchConnector. I updated the resulting Lambda's configuration to run on the same VPC and subnet as the OpenSearch instance.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/101155994/167235981-86f2b425-ec74-4d7d-ab2d-08a4f84e0e3b.png">

**Comment by andrei258258** [comment]
I have faced the same issue. Does anyone has a solution?

**Comment by ykrystal** [comment]
We made a recent change that we believe should resolve this issue. For anybody who is still experiencing this, can you please build the connector to verify if the latest changes resolve your issue? Thank you!

**Comment by samu-developments** [comment]
@ykrystal I built and deployed the current master, however facing same issue.

**Comment by ykrystal** [comment]
@samu-developments thanks for verifying. We're continuing to look at this issue.

**Comment by abhijeetkushe** [comment]
@ykrystal I am having the same issue.I too am trying to connect the Elastic Search cluster which is inside a VPC and a private subnet
