### ISSUE TITLE
[QUESTION] General question

### ISSUE THREAD

**Issue by pietvanham** [awslabs/aws-athena-query-federation#368]
I have a question that I don't think is related to a bug or feature request. 

I want to establish an SSL encrypted connection to RDS Postgres. I assume I have to put this in the connection string. Since Verify Ca is sufficient in my case, can you indicate how to get sslmode=verify-ca working in the connection string. Do I need to load the root certificate to a directory myself, or is it already somewhere I can point to?

**Comment by avirtuos** [comment]
if you are not using your own CA to sign the certificate in question that I believe the certs you need are already loaded by default. We tried to make this seamless for customers. I believe the only thing you need to do is update the connection string to make this work. Have you tried that? if so, what was the error you received?

**Comment by pietvanham** [comment]
I have tried that. This is my connection string
$postgres://jdbc:postgresql://<endpoint>:<port>/<database>?${<secrets_manager_key>}&sslmode=verify-ca

Log:
2021-03-11 15:02:14 565765b2-37e1-4080-b8b1-54e4b7bc949e WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.lang.RuntimeException: 0: org.postgresql.util.PSQLException: Could not open SSL root certificate file /home/sbx_user1051/.postgresql/root.crt.
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:108) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:236) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]

**Comment by pietvanham** [comment]
Has anyone been able to look into this one? Or should I raise it as a bug?

**Comment by henrymai** [comment]
I just tried this on the athena-postgres 2023.16.2 connector on an RDS Aurora Postgres instance with the following connection string:

```
postgres://jdbc:postgresql://some-asdf-aurora-postgres-endpoint:5432/asdf?user=someuser&password=somepassword&sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
```

Here is a screenshot of a query using that connection:

![postgres_ssl_results](https://user-images.githubusercontent.com/136857/234049390-7c79f95d-ba88-409c-8eb1-7e575abfc3d0.png)

So it looks like its working fine. Going to close this out. Please reopen this if this is still not working.
