### ISSUE TITLE
[ENHANCEMENT] `set` type from Glue crawler is throwing errors with connector DynamoDB

### ISSUE THREAD

**Issue by beaksandclaws** [awslabs/aws-athena-query-federation#378]
**Describe the bug**
I have a DynamoDB table that has the column `dataset_ids`, which is defined as a NumberSet. I've used a Glue crawler to create the table schema, which has defined the `dataset_ids` column as a `set<bigint>`. When I try to run the following query with Athena, I receive an error (stacktrace below):

```
SELECT dataset_ids FROM "dynamo-db-catalog"."default"."evt_development";
```

**To Reproduce**
1. Create a dynamo table called `evt_development`,  in which you have an item that has a key called `air_pollutants` whose value is a set: `"Carbon Monoxide"`.
2. Create and run a Glue crawler for the DynamoDB table.
3. Query the table using athena: `SELECT air_pollutants FROM "dynamo-db-catalog"."default"."evt_development";`

**Expected behavior**
Successful query.

**Screenshots / Exceptions / Errors**
Stack trace from CloudWatch:
```
2021-03-26 19:37:33 bcb26793-f025-4982-b6ea-acc55a5a0054 WARN  DynamoDBMetadataHandler:233 - doGetTable: Unable to retrieve table evt_development from AWSGlue in database/schema default. Falling back to schema inference. If inferred schema is incorrect, create a matching table in Glue to define schema (see README)
java.lang.RuntimeException: Unexpected start type set
	at com.amazonaws.athena.connector.lambda.metadata.glue.GlueFieldLexer.lexComplex(GlueFieldLexer.java:108) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.metadata.glue.GlueFieldLexer.lex(GlueFieldLexer.java:68) ~[task/:?]
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.convertField(DynamoDBMetadataHandler.java:465) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:361) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:308) ~[task/:?]
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBMetadataHandler.doGetTable(DynamoDBMetadataHandler.java:230) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:250) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
```

**Connector Details (please complete the following information):**
 - Version: 2021.6.1
 - Name: serverlessrepo-AthenaDynamoDBConnector
 - Athena Query ID: 3bf0ad2b-396a-409c-9aa9-eb798f7e273c

**Comment by juanao-fdr** [comment]
Hello, I also have this bug and is a stopper for us because we want to use **QuickSight** to create some dashboards about information from **Dynamo** and **S3**.
If we don't use the Glue Table the table is created in Athena but a lot of fields are missing so it is not an option for us.

**Comment by avirtuos** [comment]
The connector does not present support the Set data type. As a work around you can define the type of the in question field as a List. Otherwise this will require an enhancement but will still likely need to be coerced by the Connector to a LIST in the near term as support for Sets is further out. Let us know if either of these would be helpful and we can prioritize.

**Comment by henrymai** [comment]
@juanao-fdr @beaksandclaws

This pull request has been merged and should address your set type request: https://github.com/awslabs/aws-athena-query-federation/pull/728

We don't currently have plans to cut a new release with this yet, but just wanted to give you a heads up in case you wanted to build the connector with this update yourselves.

**Comment by henrymai** [comment]
@juanao-fdr @beaksandclaws

We finally cut a release (2022.30.2) with this fix. Try it out and let us know if you have any problems.
