### ISSUE TITLE
[FEATURE] DynamoDB nullable nested struct

### ISSUE THREAD

**Issue by joshuanapoli** [awslabs/aws-athena-query-federation#399]
In the DynamoDB connector, a nested struct property with value `null` is treated as an error. On the other hand, a missing property is mapped by the connector to `null`.

To be clear, I have a column with schema like this:
```
struct<id:string,nested:struct<prop:string>>
```

A DynamoDB value like this "works"; the nested struct property is absent. Through the connector, Athena gets `{id: "works", nested: null}`.
```
{
  id: "works"
}
```

A DynamoDB value like this fails; the connector throws an exception because nested is null, which does not match the `struct<prop:string>` type:
```
{
  id: "fails",
  nested: null
}
```

I'd prefer to have missing property treated the same as null value for the property; both should lead to null a value for the property in Athena.

We could add an if null return null check at https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-dynamodb/src/main/java/com/amazonaws/athena/connectors/dynamodb/resolver/DynamoDBFieldResolver.java#L80

We could potentially change the way that our application persists records to DynamoDB to be compatible with the Connector's treatment of null and missing values for nested structs. But this is the tail wagging the dog; we expect the federated query system to be flexible to adapt to our application's existing schemas.

**Comment by james-ni** [comment]
I got into same problem. 

When I have 2 items in DynamoDB table

```json
# item 1
{
  "id": "001",
  "location": {
    "suburb": {
      "name": "some_value"
    }
  }
}

# item 2
{
  "id": "002",
  "location": {
    "suburb": null
  }
}
```

The Athena query `select * from <DYNAMODB_TABLE>` failed and Lambda cloudwatch logs showed:

```
Error while processing field location: java.lang.RuntimeException
java.lang.RuntimeException: Error while processing field location
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$0(DynamoDBRecordHandler.java:193)
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:149)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
Caused by: java.lang.RuntimeException: Invalid field value encountered in DB record for field: suburb: Struct<name: Utf8>,value: null
	at com.amazonaws.athena.connectors.dynamodb.resolver.DynamoDBFieldResolver.getFieldValue(DynamoDBFieldResolver.java:96)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeStruct(BlockUtils.java:617)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:185)
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$0(DynamoDBRecordHandler.java:178)
	... 6 more
```

**Comment by ykrystal** [comment]
This issue has been resolved in [a recent PR](https://github.com/awslabs/aws-athena-query-federation/pull/780). Closing.
