### ISSUE TITLE
[BUG] ThreadPoolExecutor - metadata table with connector MySQL

### ISSUE THREAD

**Issue by mhutchings155** [awslabs/aws-athena-query-federation#456]
We use JDBC with a MySQL connector to our database. It runs first time most times without a problem, however if you rerun the query you will get a 100% reproducible error about ThreadPool exceptions. Queries run often for around 20 seconds and are only 100mb in size.

There seems to be an error with the Lambda function setting a low ThreadPoolSize when reading metadata table information:

This is the logs from CloudWatch:

`2021-07-12 12:37:05 be64bf22-40f8-4127-a2fc-d0a6c7cb5b1f INFO  JdbcSplitQueryBuilder:120 - Generated SQL : SELECT `meta_id`, `post_id`, `meta_key`, `meta_value` FROM `shop`.`wp_postmeta`
2021-07-12 12:37:07  WARN  AmazonS3Client:1903 - No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.`

And the actual error:

`2021-07-12 12:37:09 be64bf22-40f8-4127-a2fc-d0a6c7cb5b1f WARN  CompositeHandler:104 - handleRequest: Completed with an exception.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@339a3670 rejected from java.util.concurrent.ThreadPoolExecutor@6cd5122d[Running, pool size = 2, active threads = 2, queued tasks = 2, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_201]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112) ~[?:1.8.0_201]
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.spillBlock(S3BlockSpiller.java:365) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:191) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcRecordHandler.readWithConstraint(JdbcRecordHandler.java:160) ~[task/:?]
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcRecordHandler.readWithConstraint(MultiplexingJdbcRecordHandler.java:85) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_201]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]`

To Reproduce
Steps to reproduce the behaviour:

Create a connector that connects to a MySQL database that uses a metadata table
Consecutively query the metadata table 2 or 3 times in quick succession
This can also happen with a basic query like select * from meta_table on the first attempt

**Comment by mhutchings155** [comment]
Changing the default value of disable_spill_encryption from False to True seems to have fixed it. Something is going wrong with the encryption when copying to a spill bucket.
