### ISSUE TITLE
[QUESTION] HBase connection: Unable to execute HTTP request: Connect to glue.us-east-2.amazonaws.com:443

### ISSUE THREAD

**Issue by centerco** [awslabs/aws-athena-query-federation#483]
Hi, could you please help me with the Amazon Athena to HBase connection.
I work with respect to the documentation while trying to setup data source. The connector successfully connects to the HBase instance on the Amazon EMR cluster, fetches table structure... Both columns and rows ids  natively have strings as a values, but I can not prevent connector (or maybe Athena) to cast data types to some different ones: I have BIGINT or DOUBLE inside Athena table structure. Then I put to AWS Glue corresponding table structure: I have appropriate database and table inside, that equals to the names inside HBase.
But connector can't connect to AWS Glue with the following error:
```2021-09-10 08:16:06 2fb0080a-f0eb-420c-9ac6-d4f201db6c34 WARN  HbaseMetadataHandler:210 - doGetTable: Unable to retrieve table[cookie_data_store:data] from AWSGlue.
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to glue.us-east-2.amazonaws.com:443 [glue.us-east-2.amazonaws.com/3.143.132.217, glue.us-east-2.amazonaws.com/18.188.134.211, glue.us-east-2.amazonaws.com/3.12.12.20, glue.us-east-2.amazonaws.com/3.23.23.240, glue.us-east-2.amazonaws.com/3.23.109.251, glue.us-east-2.amazonaws.com/3.129.154.43] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:8202) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8169) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:8158) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.executeGetTable(AWSGlueClient.java:4774) ~[task/:?]
	at com.amazonaws.services.glue.AWSGlueClient.getTable(AWSGlueClient.java:4745) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.GlueMetadataHandler.doGetTable(GlueMetadataHandler.java:347) ~[task/:?]
	at com.amazonaws.athena.connectors.hbase.HbaseMetadataHandler.doGetTable(HbaseMetadataHandler.java:206) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:256) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132) [task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340) [LambdaSandboxJava-1.0.jar:?]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_302]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_302]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:?]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to glue.us-east-2.amazonaws.com:443 [glue.us-east-2.amazonaws.com/3.143.132.217, glue.us-east-2.amazonaws.com/18.188.134.211, glue.us-east-2.amazonaws.com/3.12.12.20, glue.us-east-2.amazonaws.com/3.23.23.240, glue.us-east-2.amazonaws.com/3.23.109.251, glue.us-east-2.amazonaws.com/3.129.154.43] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[task/:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[task/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[task/:?]
	at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[task/:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[task/:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[task/:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[task/:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[task/:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[task/:?]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?]
	... 23 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_302]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_302]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_302]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_302]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_302]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_302]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[task/:?]
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142) ~[task/:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[task/:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[task/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[task/:?]
	at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[task/:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[task/:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[task/:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[task/:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[task/:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[task/:?]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330) ~[task/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[task/:?]
```

**Comment by janmran** [comment]
The error indicates that your lambda function is unable to connect to Glue. Can you double check the VPC your lambda is running on to make sure it either has internet connection of a Glue VPC Endpoint? https://docs.aws.amazon.com/glue/latest/dg/vpc-endpoint.html

**Comment by janmran** [comment]
Closing the issue. Let me know if that wasn't able to do the trick

**Comment by scchengaiah** [comment]
I am facing a similar issue, I have created an EC2 instance with the same configuration of Lambda (Same security group, subnet )and performed a telnet to the glue end point and was able to resolve. 

But Lambda was not able to reach the glue endpoint.

Am I missing something here ?
