### ISSUE TITLE
[BUG] ssl not working with connector jdbc connector for PostgreSQL

### ISSUE THREAD

**Issue by pietvanham** [awslabs/aws-athena-query-federation#492]
When the connection PostgreSQL connection string contains SSL related parameters, the connector is not working

**To Reproduce**
1. Install template via AWS serverless repository (`https://serverlessrepo.aws.amazon.com/applications/us-east-1/292517598671/AthenaJdbcConnector`)
2. Set the env var postgres_connection_string to $postgres://jdbc:postgresql://<endpoint>:5432/<database>?${secret} and everything is working fine
3. Set the env var postgres_connection_string to $postgres://jdbc:postgresql://<endpoint>:5432/<database>?${secret}&sslmode=require and everything is working fine
4. Set the env var postgres_connection_string to $postgres://jdbc:postgresql://<endpoint>:5432/<database>?${secret}&sslmode=verify-ca and it stops working with the error message:
`Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: 0: org.postgresql.util.PSQLException: Could not open SSL root certificate file /home/sbx_user1051/.postgresql/root.crt.`

**Expected behavior**
I expect that the connector would also work with SSL enabled

**Error message cloudwatch**
`0: org.postgresql.util.PSQLException: Could not open SSL root certificate file /home/sbx_user1051/.postgresql/root.crt.: java.lang.RuntimeException
java.lang.RuntimeException: 0: org.postgresql.util.PSQLException: Could not open SSL root certificate file /home/sbx_user1051/.postgresql/root.crt.
	at com.amazonaws.connectors.athena.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:109)
	at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doGetTable(JdbcMetadataHandler.java:215)
	at com.amazonaws.connectors.athena.jdbc.MultiplexingJdbcMetadataHandler.doGetTable(MultiplexingJdbcMetadataHandler.java:116)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)`

**Comment by pietvanham** [comment]
Sorry for the mess (closed --> reopen)
Seems like it is working for require, but not for verify-ca

**Comment by janmran** [comment]
Looks like the rds cert isn't chained to any of the default jre certs. Thinking we may have to package it in. Also like the redshift driver already has the cert packaged into itself somehow since ssl is working for redshift clusters.
