### ISSUE TITLE
[BUG] not authorized on <database> to execute command { find: "system.views" } with connector athena-docdb

### ISSUE THREAD

**Issue by theFlyRoper** [awslabs/aws-athena-query-federation#506]
**Describe the bug**
DocumentDB fails when connecting to MongoDB if there are any collections in the current database that the connector account lacks access to. 

**To Reproduce**
1. Deploy athena-docdb connector with connection string for mongodb Atlas (https://www.mongodb.com/atlas/database)
2. Load the data source in the AWS console Athena query editor 
3. If there is a collection which the connecting account lacks permission to read, the docdb connector fails entirely.

**Expected behavior**
If the account lacks permission to read the collection, the connector should move to the next collection and not show the forbidden collection in the list of athena database tables.  Or it should show some indicator that the connector lacks read access to that collection.

**Screenshots / Exceptions / Errors**
![Athena_DocDB_BugReport_2021-10-21](https://user-images.githubusercontent.com/16727819/140528864-3cdf0951-e044-4474-8737-07b405fa52f5.png)
Here is more of the error text:
Failed to get metadata for table (system.views) from lambda function due to java.lang.RuntimeException: com.amazonaws.services.lambda.invoke.LambdaFunctionException: Query failed with error code 13 and error message 'not authorized on <database> to execute command { find: "system.views", limit: 10, batchSize: 10,, $clusterTime: { clusterTime: Timestamp(1634825858, 1), signature: { hash: BinData(0, <hash>), keyId: <key> } }, lsid: { id: UUID("00002000-efef-4444-b425-a7ae91a587b5") } }' on server <mongodb server>:27017

Trace:
Query failed with error code 13 and error message 'not 
authorized on <database> to execute command { find: "system.views", limit: 10, batchSize: 10, $db: "<database>", $clusterTime: { clusterTime: Timestamp(1634825858, 1), signature: { hash: BinData(0, 4F26FA56443940708650AF6D9B303D29A05723A7), keyId: 6964759163792523267 } }, lsid: { id: UUID("be502000-e864-4f18-b425-a7ae91a587b5") } }' on server <database>:27017: com.mongodb.MongoQueryException
com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on <database> to execute command { find: "system.views", limit: 10, batchSize: 10, $db: "<database>", $clusterTime: { clusterTime: Timestamp(1634825858, 1), signature: { hash: BinData(0, 4F26FA56443940708650AF6D9B303D29A05723A7), keyId: 6964759163792523267 } }, lsid: { id: UUID("be502000-e864-4f18-b425-a7ae91a587b5") } }' on server <servername>.mongodb.net:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:707)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:696)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:462)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:696)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:83)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:132)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:86)
	at com.amazonaws.athena.connectors.docdb.SchemaUtils.inferSchema(SchemaUtils.java:79)
	at com.amazonaws.athena.connectors.docdb.DocDBMetadataHandler.doGetTable(DocDBMetadataHandler.java:206)
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:257)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)

**Connector Details (please complete the following information):**
 - Version: serverlessrepo:semanticVersion | 2021.37.1
serverlessrepo:applicationId | arn:aws:serverlessrepo:us-east-1:292517598671:applications/AthenaDocumentDBConnector
 - Name: AthenaDocumentDBConnector

**Comment by markopy** [comment]
I get the same error after adding a view to my database because doing so implicitly creates the `system.views` collection which is used by mongodb internally and not actually accessible (even by admin users).

It appears this bug makes it impossible to use the connector with any mongodb database that contains views. 

As @theFlyRoper pointed out the proper fix would be to ignore all collections for which access fails during the discovery/schema inference stage.
If this is a complicated fix perhaps all `system.*` collections can be explicitly excluded instead since they should never be accessed anyway?

@henrymai @nauy2697

**Comment by chngpe** [comment]
Hi, 

Which mongoDB version are you running? and with Admin rights you are facing the issue? Can you also share the log?

**Comment by n-dallacosta** [comment]
Hi @chngpe, I am using MongoDB Atlas 6.0.11. With "admin right" I mean the user has the "Atlas admin" build-in role.

Below are the error logs

> WARN  CompositeHandler:116 - handleRequest: Completed with an exception.
> com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on DATABASE_NAME to execute command { find: "system.views", limit: 10, batchSize: 10, $db: "DATABASE_NAME", $clusterTime: { clusterTime: Timestamp(1700226748, 4), signature: { hash: BinData(0, C722CC9B7385DACD8DD8E5B2198AE67A1DEE90E1), keyId: 7244667830354837505 } }, lsid: { id: UUID("b1df6a8b-f138-40ec-a9ae-b0e39227e331") } }' on server SHARD_NAME.mongodb.net:27017

**Comment by macohen** [comment]
@chngpe what's the best way to go about validating that this is or is not fixed?
