### ISSUE TITLE
[BUG]  Could not find table in <<database>> with connector JDBC Connector (Mysql Aurora)

### ISSUE THREAD

**Issue by rs-alexis** [awslabs/aws-athena-query-federation#508]
**Describe the bug**
I am facing this intermittent issue using the JDBC connector. Sometime when I query my DB (Mysql 5.6 hosted on AWS aurora) through Athena JDBC connector, I see this intermittent issue popping up:
```executed in context[retrieving meta-data] with message[Could not find table in site_1306].```
After retrying the same request, most of the time it won't error again. Weird.

I also noticed that it tend to happen when I'm running queries that hits the same db more than one time.

**To Reproduce**
There is not deterministic way of reproducing this issue. Query with high load the same Aurora Database (MySQL 5.6?). Maybe you would see the issue happening.
But After initial investigation, it appears that the following method `getColumns` (https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-jdbc/src/main/java/com/amazonaws/athena/connectors/jdbc/manager/JdbcMetadataHandler.java#L273) sometimes returns an empty set.

**Expected behavior**
I know that the table exists in the database. it should return it.

**Screenshots / Exceptions / Errors**
Stacktrace:
```
Field | Value
-- | --
@ingestionTime | 1634852590489
@log | 362213751741:/aws/lambda/sls-athena-data-connector-lambda-prd-rsapi
@logStream | 2021/10/21/[$LATEST]cdafbbc872f8440d8ae6f30c033f78e2
@message | Could not find table in site_1306: java.lang.RuntimeExceptionjava.lang.RuntimeException: Could not find table in site_1306at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.getSchema(JdbcMetadataHandler.java:259)at com.amazonaws.connectors.athena.jdbc.manager.JdbcMetadataHandler.doGetTable(JdbcMetadataHandler.java:217)at com.retentionscience.athena.rsapi.RsapiMetadataHandler.doGetTable(RsapiMetadataHandler.java:114)at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:256)at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:132)at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
@timestamp | 1634852588571
```

**Connector Details (please complete the following information):**
 - Version: 2021.27.1
 - Name jdbc
 - Athena Query IDs f989fafb-97a3-4558-be25-da12ad91562f

**Comment by hackett123** [comment]
This is an old ticket, but my suspicion is that the [DatabaseMetaData](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html) getColumns() call is throwing a SQLException, likely a [SQLTimeoutException](https://docs.oracle.com/javase/8/docs/api/java/sql/SQLTimeoutException.html), and that the calling method in our JdbcMetadataHandler is swallowing it by virtue of it being called in a try-with-resources statement.

What I will do is fix this method to catch exceptions, log the error, and throw the caught exception. Today's behavior throws a RuntimeException if the table wasn't found, but completely loses the context on what the issue was. I'll link a PR to this ticket once it's up. If any customer is facing issues related to this, we will now be able to more easily help them find the root cause.

**Comment by hackett123** [comment]
You can publish your lambda function as a new version if you want to make sure you can revert back to your existing setup.

**Comment by hackett123** [comment]
I'm going to close this out for now as it's been 10 days since contact. Please re-open the ticket if you are facing issues with this still on the latest JAR.
