### ISSUE TITLE
[BUG] No Suitable Driver found for PostgreSQL 13

### ISSUE THREAD

**Issue by jbrant** [awslabs/aws-athena-query-federation#685]
**Describe the bug**
Attempting to connect to a PostgreSQL 13.3 RDS instance yields "no suitable driver found" message. JDBC connection string is formatted per instructions:

`postgres://jdbc:postgresql://<server>:5432/<database>?user=<username>&password=<password>`

**To Reproduce**
1. Create AthenaPostgreSQLConnector lambda and point connection string to PostgreSQL 13+ database
2. Go to "Data sources" in Athena and create a new PostgreSQL data source that references the lambda function in step 1
3. Go to the Athena "Query Editor" and select the newly created data source from the "Data source" drop-down
4. Click the "Database" drop-down and note "no suitable driver" exception

**Expected behavior**
Databases for the configured server should have been enumerated in the "Database" drop-down.

**Screenshots / Exceptions / Errors**
`java.lang.RuntimeException: 0: java.sql.SQLException: No suitable driver found for jdbc:postgresql://<hostname>:5432/<database>?user=<user>&password=<password>
at com.amazonaws.athena.connectors.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:94)
at com.amazonaws.athena.connectors.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129)
at com.amazonaws.athena.connectors.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102)
at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:243)
at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)`

**Connector Details (please complete the following information):**
 - Version: 2022.10.1
 - Name: postgres

**Comment by andersonptf** [comment]
Any idea on how to solve this?

**Comment by akuzin1** [comment]
Thank you for reaching out. Using the latest version (2022.47.1) of the PostgreSQL connector and a PostgreSQL 13.3 RDS instance, I was unable to recreate the issue encountered above. I recommend upgrading to latest version of the connector and trying again.
