### ISSUE TITLE
[BUG] No suitable driver found for jdbc:snowflake with connector athena-snowflake

### ISSUE THREAD

**Issue by slyp-leo** [awslabs/aws-athena-query-federation#702]
**Describe the bug**
Attempting to connect to a Snowflake instance yields "no suitable driver found" error message. JDBC connection string is formatted per instructions:

`snowflake://jdbc:snowflake://MO16234.ap-southeast-2.snowflakecomputing.com/?warehouse=<WH name>&db= <db name>&schema=public&user=<username>&password=<password>&role=<account role>`

**To Reproduce**

- Go to Athena data sources and click create new data source, select snowflake.
- Deploy the connector by following the instructions
- Go to the Athena "Query Editor" and select the newly created data source from the "Data source" drop-down
- Found the "no suitable driver" exception

**Expected behaviour**
Able to query the tables under the new snowflake data source

**Screenshots / Exceptions / Errors**
java.lang.RuntimeException: 0: java.sql.SQLException: No suitable driver found for `jdbc:snowflake://MO16234.ap-southeast-2.snowflakecomputing.com/?warehouse=<WH name>&db= <db name>&schema=public&user=<username>&password=<password>&role=<account role>`
	at com.amazonaws.athena.connectors.jdbc.connection.GenericJdbcConnectionFactory.getConnection(GenericJdbcConnectionFactory.java:94) ~[task/:?]
	at com.amazonaws.athena.connectors.jdbc.manager.JdbcMetadataHandler.doListSchemaNames(JdbcMetadataHandler.java:129) ~[task/:?]
	at com.amazonaws.athena.connectors.jdbc.MultiplexingJdbcMetadataHandler.doListSchemaNames(MultiplexingJdbcMetadataHandler.java:102) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.MetadataHandler.doHandleRequest(MetadataHandler.java:243) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:262) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:199) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:193) [aws-lambda-java-runtime-0.2.0.jar:?]

**Comment by slyp-leo** [comment]
This issue is quite similar to: https://github.com/awslabs/aws-athena-query-federation/issues/685

**Comment by slyp-leo** [comment]
The issue is related to a type in the connection string

**Comment by henrymai** [comment]
> The issue is related to a type in the connection string

Any details on what the typo was?

Just wondering because it might be common enough to make this typo that it might help resolve the other issue as well: https://github.com/awslabs/aws-athena-query-federation/issues/685
