### ISSUE TITLE
[BUG] "Invalid operator used in KeyConditionExpression: OR" with a WHERE statement with connector athena-dynamodb

### ISSUE THREAD

**Issue by ahardin13** [awslabs/aws-athena-query-federation#746]
**Describe the bug**
With a simple, single-table query with multiple statements in a WHERE clause, we are getting the error 
```
GENERIC_USER_ERROR: Encountered an exception[com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException] from your LambdaFunction[arn:aws:lambda:us-east-1:#####:function:dynamodbdata] executed in context[S3SpillLocation{bucket='bucket-name', key='athena-spill/{guid}/{guid}', directory=true}] with message[Invalid operator used in KeyConditionExpression: OR (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: T6MH1CEDVQHUVMJEBGLT7D5N3VVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)]
This query ran against the "default" database, unless qualified by the query. Please post the error message on our [forum ](https://forums.aws.amazon.com/forum.jspa?forumID=242&start=0) or contact [customer support ](https://us-east-1.console.aws.amazon.com/support/home?#/case/create?issueType=technical&serviceCode=amazon-athena&categoryCode=query-related-issue) with Query Id: c0a11026-a940-4148-afaa-102f92b63d52
```

Example query:
```
select <columns>
from <table>
where
  owner = 'guid' and
  kind = 'kind' and
  status = 'active' and
  year = 2021
```

After changing year to `year >= 2021`, the query will succeed. However, then adding `and year <= 2021` to restrict it will fail with the same above error.

There is a global secondary index on year and status. Perhaps it's trying to use that with an `OR`?

**To Reproduce**
1. Run a query with a `where` clause such as above against the table.

**Expected behavior**
The query succeeds.

**Screenshots / Exceptions / Errors**
```
Invalid operator used in KeyConditionExpression: OR (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: T6MH1CEDVQHUVMJEBGLT7D5N3VVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null): com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Invalid operator used in KeyConditionExpression: OR (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: T6MH1CEDVQHUVMJEBGLT7D5N3VVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:5136)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5103)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:2883)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:2849)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.lambda$next$19(DynamoDBRecordHandler.java:301)
	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:187)
	at com.amazonaws.athena.connector.lambda.ThrottlingInvoker.invoke(ThrottlingInvoker.java:167)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:301)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler$4.next(DynamoDBRecordHandler.java:278)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$17(DynamoDBRecordHandler.java:150)
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:149)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:138)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)
```

**Connector Details (please complete the following information):**
 - Version: 2022.2.1
 - Name: athena-dynamodb
 - Athena Query IDs: `c0a11026-a940-4148-afaa-102f92b63d52`

**Comment by henrymai** [comment]
Hey @ahardin13 

I think this has been fixed with this patch: https://github.com/awslabs/aws-athena-query-federation/pull/787

Can you try the latest version of the DDB connector to see if you're still facing this issue; when you use: `year >= 2021 AND year <= 2021`?

**Comment by henrymai** [comment]
Closing this out since there hasn't been a reply for a month. Please re-open if this issue is still present with the latest version of the DDB connector.
