### ISSUE TITLE
[BUG] ClassCastException with connector DocumentDB

### ISSUE THREAD

**Issue by MVigialnte** [awslabs/aws-athena-query-federation#790]
**Describe the bug**
When query a DocumentDB collection storing GeoJSON data the lambda function is throwing a ClassCastException.
Below the excpetion thrown.

**To Reproduce**
1. Connect a DocumentDB cluster to Athena
2. Execute a query over a collection containing GeoJSON objects

**Expected behavior**
Should work

**Screenshots / Exceptions / Errors**
Error while processing field geoPoint: java.lang.RuntimeException
java.lang.RuntimeException: Error while processing field geoPoint
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:158)
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:183)
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.readWithConstraint(DocDBRecordHandler.java:136)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:192)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:158)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:138)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:103)
Caused by: java.lang.RuntimeException: Unable to write value for field $data$ using value 0 with minor type FLOAT8
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeSimpleValue(BlockUtils.java:1027)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeAllValue(BlockUtils.java:765)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeList(BlockUtils.java:616)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeAllValue(BlockUtils.java:754)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeStruct(BlockUtils.java:651)
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setComplexValue(BlockUtils.java:211)
	at com.amazonaws.athena.connector.lambda.data.Block.offerComplexValue(Block.java:218)
	at com.amazonaws.athena.connectors.docdb.DocDBRecordHandler.lambda$readWithConstraint$0(DocDBRecordHandler.java:147)
	... 6 more
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.writeSimpleValue(BlockUtils.java:855)
	... 13 more

**Connector Details (please complete the following information):**
 - Version: 2022.38.1
 - Name serverlessrepo-AthenaDocumentDBConnector
 - Athena Query IDs 4ffc0885-7eed-41a3-bb9f-937aea8b5887

**Additional context**

**Comment by ykrystal** [comment]
Fix merged in. Closing ticket.
