### ISSUE TITLE
[BUG] "Access denied for user '[USERNAME]'@'[IP]' (using password: YES)" with connector MySQL

### ISSUE THREAD

**Issue by eliotstock** [awslabs/aws-athena-query-federation#801]
I have a MySQL database instance in AWS RDS. I'd like to access it using AWS Athena. I used the "Amazon Athena Lambda MySQL Connector" to set up the new Data Source:

https://github.com/awslabs/aws-athena-query-federation/tree/master/athena-mysql

I installed this using the Serverless Application Repository. Here's the application:

https://serverlessrepo.aws.amazon.com/applications/us-east-1/292517598671/AthenaMySQLConnector

In the application settings before deploying, I used the same SecurityGroupIDs and SubnetIds as I used in another lambda function that is able to query the same database just fine.

In the environment variables for the lambda, I have the connection string set under both the key `default` and `rds_mysql_connection_string` (`rds_mysql` is the name of the Data Source in Athena). The connection string is in the format:

```
mysql://jdbc:mysql://HOSTNAME.us-east-1.rds.amazonaws.com:3306/DBNAME?user=USERNAME&password=PASSWORD
```

When I try to switch to the new data source in the Athena query editor, I get this error:

```
Access denied for user '[USERNAME]'@'[IP]' (using password: YES)
```

I diff'ed the role for the lambda that can connect against the one for the connector and they're pretty much the same. I even tried giving the connector the exact same role for a minute but it didn't help.

Using the test button on the lambda function for the connector also throws an error, but this could be a red herring. I use a blank test event and I get this in the logs:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Transforming org/apache/logging/log4j/core/lookup/JndiLookup (lambdainternal.CustomerClassLoader@1a6c5a9e)
START RequestId: 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a Version: $LATEST
2022-10-20 03:38:51 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a INFO  BaseAllocator:58 - Debug mode disabled.
2022-10-20 03:38:51 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a INFO  DefaultAllocationManagerOption:97 - allocation manager type not specified, using netty as the default type
2022-10-20 03:38:51 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a INFO  CheckAllocator:73 - Using DefaultAllocationManager at memory/DefaultAllocationManagerFactory.class
2022-10-20 03:38:51 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a WARN  CompositeHandler:107 - handleRequest: Completed with an exception.
java.lang.IllegalStateException: Expected field name token but got END_OBJECT
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:221) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getType(BaseDeserializer.java:295) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:56) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49) ~[task/:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74) ~[task/:?]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[task/:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[task/:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666) ~[task/:?]
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99) [task/:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:899) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:206) [aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:200) [aws-lambda-java-runtime-0.2.0.jar:?]
Expected field name token but got END_OBJECT: java.lang.IllegalStateException
java.lang.IllegalStateException: Expected field name token but got END_OBJECT
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.assertFieldName(BaseDeserializer.java:221)
	at com.amazonaws.athena.connector.lambda.serde.BaseDeserializer.getType(BaseDeserializer.java:295)
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.doDeserialize(DelegatingDeserializer.java:56)
	at com.amazonaws.athena.connector.lambda.serde.DelegatingDeserializer.deserializeWithType(DelegatingDeserializer.java:49)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:99)

END RequestId: 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a
REPORT RequestId: 98cdd329-b0e5-49c4-8c9e-ae7b6f51dc2a	Duration: 343.41 ms	Billed Duration: 344 ms	Memory Size: 3008 MB	Max Memory Used: 170 MB	Init Duration: 2665.96 ms	
```

**Connector Details (please complete the following information):**
 - Version: 2022.39.1
 - Name mysql
 - Athena Query IDs [if applicable]

**Comment by hackett123** [comment]
Hi [eliotstock](https://github.com/eliotstock), let me take a look. This sounds to me like a configuration issue. The mysql JDBC connection string should look like this: `mysql://jdbc:mysql://USER:PASSWORD@HOST.REGION.rds.amazonaws.com:3306/DB_NAME`

Your format is `mysql://jdbc:mysql://HOSTNAME.us-east-1.rds.amazonaws.com:3306/DBNAME?user=USERNAME&password=PASSWORD`.

When I use my format, I can query my MySQL db from Athena. If I modify my connection string to use yours, I get the error `GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[mysql] executed in context[retrieving meta-data] with message[1045: java.sql.SQLException: Access denied for user ''@<IP_REDACTED> (using password: NO)]`

I believe the difference in my message having `(using password: NO)` and yours having `(using password: YES)` is just a difference in our MySQL db configuration.


Can you confirm that after modifying your jdbc connection string format, you can connect? This looks like our documentation has a mistake, and I will get that updated.

**Comment by eliotstock** [comment]
Thanks, but using your format I get this error on the Athena UI:

```
Failed to invoke lambda function due to com.amazonaws.services.lambda.invoke.LambdaFunctionException: 0: java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Failed to parse the host:port pair '[USERNAME]:[PASSWORD]'.
```

So the driver's expecting to find a host and port at these positions in the connection string. I don't know how yours is working. Perhaps you're using a different version of the connector or it's not really using the env var you've set.

**Comment by hackett123** [comment]
Hi Eliot,

I was using an older connector version, but I just tested again against the latest and still see the same behavior. I also tested by deleting the username:password, replacing the password with a wrong password, and replacing the username with a different username, and received expected output on all of them (all changes threw errors).

Looking online I saw that sometimes a missing slash or similar can lead to the error you're facing. Can you please confirm that you are following exactly the string template `mysql://jdbc:mysql://<user>:<password>@<host>.<region>.rds.amazonaws.com:<port>/<db_name>`?

**Comment by eliotstock** [comment]
Yes, I've checked.

In the end the only way I found to get this working was to put the username and password into the Secrets Manager and refer to the secret using `?${secret_name}` on the end of the connection string.

At the very least I'd suggest a docs update to give the JDBC connection string format. All the docs (see link above) say is `mysql://${jdbc_connection_string}`.

**Comment by hackett123** [comment]
In the connector code, the secrets manager will just do a pure find and replace of the `${secret_name}` with whatever you put in secrets manager.

I used an RDS MySQL cluster with user/password auth. Both of the following JDBC formats allowed me to query my table:

1. `mysql://jdbc:mysql://USERNAME:PASSWORD@HOST.REGION.rds.amazonaws.com:PORT/DB`
2. `mysql://jdbc:mysql://HOST.REGION.rds.amazonaws.com:PORT/DB?user=USER&password=PASSWORD`

If I do not provide a user/password and just use format `mysql://jdbc:mysql://HOST.REGION.rds.amazonaws.com:PORT/DB`, the query fails as expected, with error `GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[<OBSCURED>] executed in context[retrieving meta-data] with message[java.sql.SQLException: Access denied for user '<OBSCURED>'@'<OBSCURED_IP>' (using password: NO)]`


I have given an ask to our documentation writer to update the AWS docs to include the two valid formats because it is not a great user experience to have to google around for jdbc connection string formats.

With all that being said, I am not sure what the customer above faced issues given I could not reproduce the issue. I will resolve this, but if any issue emerges from any customer, please feel free to re-open.

**Comment by markotitel** [comment]
This is from CloudWatch logs:

![image](https://user-images.githubusercontent.com/5695612/233093393-02e6007b-4891-4af4-b26b-95d8420ae888.png)

If some version information is useful, the screenshot is the log from one lambda execution which is triggered when we try to select database in athena.

**Comment by henrymai** [comment]
@markotitel 

Your connection string says:

```
mysql://jdbc:mysql://some-prod-db-snapshot.123123313.us-west-2.rds.amazonaws.com:3306/somedatabase?user=readonly&pass=123asdqwe
```

`pass=123asdfqwe` should be `password=123asdfqwe`

Try that and see if it helps.

**Comment by evbo** [comment]
@hackett123 `?${secrets_name}` for me doesn't appear to work because my secrets manager has illegal characters, such as `!` that need to be urlencoded or else I get an exception that the connection string is wrong. But if I urlencode them, I get the exception above in this thread (meaning user/password isn't correct).

What works is manually gathering the user and password from SecretsManager, urlencoding them, and then updating the connection string with them (RDS auto rotates password every 7 days) in the Lambda env var configuration. This feels insecure storing user/password in plain text in a lambda env var.

I see there's a configuration field during the Lambda creation for specifying a `SecretNamePrefix` but it isn't clear what that does. I made sure to enter the name of my secret, but nothing seemed to happen as a result. 

Could maybe this issue be reopened to clarify how to get SecretsManager secrets configured so as to avoid modifying the connection string manually like this?
