### ISSUE TITLE
DynamoDB Connector does not handle Glue BigInt column correctly

### ISSUE THREAD

**Issue by atennak1** [awslabs/aws-athena-query-federation#81]
I crawled a table containing a year column which the Glue crawler decided was a `bigint`.  I see the following stacktrace in CloudWatch:

```
Error while processing field year: java.lang.RuntimeException
java.lang.RuntimeException: Error while processing field year
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$1(DynamoDBRecordHandler.java:185)
	at com.amazonaws.athena.connector.lambda.data.S3BlockSpiller.writeRows(S3BlockSpiller.java:174)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.readWithConstraint(DynamoDBRecordHandler.java:146)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doReadRecords(RecordHandler.java:191)
	at com.amazonaws.athena.connector.lambda.handlers.RecordHandler.doHandleRequest(RecordHandler.java:157)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:135)
	at com.amazonaws.athena.connector.lambda.handlers.CompositeHandler.handleRequest(CompositeHandler.java:100)
Caused by: java.lang.RuntimeException: Unable to set value for field year using value 1933
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setValue(BlockUtils.java:330)
	at com.amazonaws.athena.connector.lambda.data.Block.offerValue(Block.java:175)
	at com.amazonaws.athena.connectors.dynamodb.DynamoDBRecordHandler.lambda$readWithConstraint$1(DynamoDBRecordHandler.java:176)
	... 6 more
Caused by: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Long
	at com.amazonaws.athena.connector.lambda.data.BlockUtils.setValue(BlockUtils.java:288)
	... 8 more
```

This is because the ItemUtils.toSimpleValue util that is used to convert from AttributeValue to Java object returns a BigDecimal for any DDB Number attribute.

**Comment by atennak1** [comment]
Handled for top level (non-nested) DDB attributes with https://github.com/awslabs/aws-athena-query-federation/commit/d3b25cb6bef865f51cfd5e19e9d9512b29f48015

**Comment by avirtuos** [comment]
closing issue as it seems we have already pushed the fix. @atennak1 please reopen if you were planning a phase 2 to this.
